name: md2mld CI
on:
  - push
  - pull_request
jobs:
  run:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # no special functionality to test in macos-latest or windows-latest
        operating-system: [ubuntu-latest]
        ocaml-compiler:
          - 4.12.x
          - 4.11.x
          - 4.10.x
          - 4.09.x
          - 4.08.x
          - 4.07.x
          - 4.06.x
          - 4.05.x
          - 4.04.x
    steps:
    - uses: actions/checkout@master
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
    - if: ${{ matrix.ocaml-compiler == '4.12.x' }}
      run: |
        opam install ocamlformat
        opam exec -- dune build @fmt
    - run: opam pin add md2mld.dev . --no-action
    - run: opam install md2mld --yes --deps-only
    - run: opam install -t md2mld
